services:
  app:
    build:
      context: .
      dockerfile: ./cmd/account_api/Dockerfile
    container_name: go_app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: account_api
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "9090:9090"

  postgres:
    image: postgres:18.0
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: account_api
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
      - ./internal/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
